server:
  port: 8099
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes:
      - id: micro-crud
        uri: localhost:8080
        predicates:
        - Path=/micro-crud/**
